import { Metadata } from "next";

export const metadata: Metadata = {
  title: "StayHub",
  description: "Generated by create next app",
};

interface AuthLayoutProps {
  children: React.ReactNode;
}

const AuthLayout: React.FC<AuthLayoutProps> = ({ children }) => {
  return <section>{children}</section>;
};

export default AuthLayout;
