import { FC } from "react";
import "./globals.css";
import type { Metadata } from "next";

import { Inter } from "next/font/google";
import NavBar from "@/components/navbar/NavBar";
import ToasterProvider from "@/context/ToasterProvider";
import getCurrentUser from "@/actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StayHub",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: FC<RootLayoutProps> = async ({ children }) => {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider />
        <NavBar currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
